# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouter_classe.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import first
class Ui_Add_class(object):
    def setupUi(self, Add_class):
        Add_class.setObjectName("Add_class")
        Add_class.resize(439, 223)
        Add_class.setMinimumSize(QtCore.QSize(439, 223))
        Add_class.setMaximumSize(QtCore.QSize(439, 223))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Add_class.setWindowIcon(icon)
        Add_class.setWindowTitle("  ")
        self.centralwidget = QtWidgets.QWidget(Add_class)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-390, -220, 1001, 631))
        self.frame.setStyleSheet("border-image: url(:/newPrefix/revue et correction_Plan de travail 1 copie 5.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(550, 250, 201, 21))
        self.frame_2.setStyleSheet("border-image: url(:/newPrefix/15.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(550, 290, 201, 20))
        self.frame_3.setStyleSheet("border-image: url(:/newPrefix/15.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.NIVEAU = QtWidgets.QComboBox(self.frame_3)
        self.NIVEAU.setGeometry(QtCore.QRect(0, 0, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.NIVEAU.setFont(font)
        self.NIVEAU.setObjectName("NIVEAU")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.NIVEAU.addItem("")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(550, 326, 201, 21))
        self.frame_4.setStyleSheet("border-image: url(:/newPrefix/15.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.SERIE = QtWidgets.QComboBox(self.frame_4)
        self.SERIE.setGeometry(QtCore.QRect(0, 0, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.SERIE.setFont(font)
        self.SERIE.setObjectName("SERIE")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.SERIE.addItem("")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(550, 366, 201, 20))
        self.frame_5.setStyleSheet("border-image: url(:/newPrefix/15.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.NUMER = QtWidgets.QSpinBox(self.frame_5)
        self.NUMER.setGeometry(QtCore.QRect(0, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.NUMER.setFont(font)
        self.NUMER.setMinimum(1)
        self.NUMER.setObjectName("NUMER")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(650, 400, 54, 25))
        self.frame_6.setStyleSheet("border-image: url(:/newPrefix/6.png);\n""background-color: rgb(11, 170, 75);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.valider = QtWidgets.QPushButton(self.frame_6)
        self.valider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.valider.setGeometry(QtCore.QRect(0, 0, 54, 25))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.valider.setFont(font)
        self.valider.setStyleSheet("background-color: rgb(11, 170, 75);\n"
"color: rgb(255, 255, 255);")
        self.valider.setObjectName("valider")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(710, 400, 54, 25))
        self.frame_7.setStyleSheet("border-image: url(:/newPrefix/15.png);\n"
"background-color: rgb(11, 170, 75);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.annuler = QtWidgets.QPushButton(self.frame_7)
        self.annuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.annuler.setGeometry(QtCore.QRect(0, 0, 54, 25))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.annuler.setFont(font)
        self.annuler.setStyleSheet("color: rgb(11, 170, 75);")
        self.annuler.setObjectName("annuler")
        Add_class.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_class)
        QtCore.QMetaObject.connectSlotsByName(Add_class)

    def retranslateUi(self, Add_class):
        _translate = QtCore.QCoreApplication.translate
        self.NIVEAU.setItemText(0, _translate("Add_class", "6ème"))
        self.NIVEAU.setItemText(1, _translate("Add_class", "5ème"))
        self.NIVEAU.setItemText(2, _translate("Add_class", "4éme"))
        self.NIVEAU.setItemText(3, _translate("Add_class", "3ème"))
        self.NIVEAU.setItemText(4 , _translate("Add_class", "2nd"))
        self.NIVEAU.setItemText(5, _translate("Add_class", "1ère"))
        self.NIVEAU.setItemText(6, _translate("Add_class", "Tle"))
        self.SERIE.setItemText(1, _translate("Add_class", "D"))
        self.SERIE.setItemText(2, _translate("Add_class", "C"))
        self.SERIE.setItemText(3, _translate("Add_class", "A"))
        self.SERIE.setItemText(4, _translate("Add_class", "A1"))
        self.SERIE.setItemText(5, _translate("Add_class", "A2"))
        self.SERIE.setItemText(6, _translate("Add_class", "B"))
        self.SERIE.setItemText(7, _translate("Add_class", "G1"))
        self.SERIE.setItemText(8, _translate("Add_class", "G2"))
        self.SERIE.setItemText(9, _translate("Add_class", "AB"))
        self.SERIE.setItemText(10, _translate("Add_class", "F1"))
        self.SERIE.setItemText(11, _translate("Add_class", "F2"))
        self.SERIE.setItemText(12, _translate("Add_class", "F3"))
        self.SERIE.setItemText(13, _translate("Add_class", "T"))
        self.SERIE.setItemText(14, _translate("Add_class", "E"))
        self.SERIE.setItemText(15, _translate("Add_class", "H1"))
        self.SERIE.setItemText(16, _translate("Add_class", "H2"))
        self.SERIE.setItemText(17, _translate("Add_class", "H3"))
        self.valider.setText(_translate("Add_class", " Entrer"))
        self.annuler.setText(_translate("Add_class", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_class = QtWidgets.QMainWindow()
    ui = Ui_Add_class()
    ui.setupUi(Add_class)
    Add_class.show()
    sys.exit(app.exec_())

