# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_acceuil.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import first
class Ui_Page_Acceuil(object):
    def setupUi(self, Page_Acceuil):
        Page_Acceuil.setObjectName("Page_Acceuil")
        Page_Acceuil.resize(989, 601)
        Page_Acceuil.setMaximumSize(QtCore.QSize(989, 601))
        Page_Acceuil.setMaximumSize(QtCore.QSize(989, 601))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Page_Acceuil.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Page_Acceuil)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 989, 601))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(17)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-image: url(:/newPrefix/revue et correction_Plan de travail 1 copie 4.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 387, 152, 59))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(:/newPrefix/6.png);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(510, 387, 371, 59))
        self.frame_2.setStyleSheet("border-image: url(:/newPrefix/15.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 0, 361, 56))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        Page_Acceuil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Page_Acceuil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 23))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuEtablissemnt = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menuEtablissemnt.setFont(font)
        self.menuEtablissemnt.setObjectName("menuEtablissemnt")
        self.menuClasse = QtWidgets.QMenu(self.menubar)
        self.menuClasse.setObjectName("menuClasse")
        Page_Acceuil.setMenuBar(self.menubar)
        self.actionAjouter = QtWidgets.QAction(Page_Acceuil)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/AJOUTER.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjouter.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter.setFont(font)
        self.actionAjouter.setObjectName("actionAjouter")
        self.actionVoir = QtWidgets.QAction(Page_Acceuil)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/VOIR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoir.setIcon(icon1)
        self.actionVoir.setObjectName("actionVoir")
        self.actionAjouter_2 = QtWidgets.QAction(Page_Acceuil)
        self.actionAjouter_2.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter_2.setFont(font)
        self.actionAjouter_2.setObjectName("actionAjouter_2")
        self.actionVoir_une_classe = QtWidgets.QAction(Page_Acceuil)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/VOIR ENSEMBLE-05.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoir_une_classe.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionVoir_une_classe.setFont(font)
        self.actionVoir_une_classe.setObjectName("actionVoir_une_classe")
        self.actionVoir_l_ensemble_des_classes = QtWidgets.QAction(Page_Acceuil)
        self.actionVoir_l_ensemble_des_classes.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionVoir_l_ensemble_des_classes.setFont(font)
        self.actionVoir_l_ensemble_des_classes.setObjectName("actionVoir_l_ensemble_des_classes")
        self.menuEtablissemnt.addAction(self.actionAjouter)
        self.menuEtablissemnt.addAction(self.actionVoir)
        self.menuClasse.addAction(self.actionAjouter_2)
        self.menuClasse.addAction(self.actionVoir_une_classe)
        self.menuClasse.addAction(self.actionVoir_l_ensemble_des_classes)
        self.menubar.addAction(self.menuEtablissemnt.menuAction())
        self.menubar.addAction(self.menuClasse.menuAction())

        self.retranslateUi(Page_Acceuil)
        QtCore.QMetaObject.connectSlotsByName(Page_Acceuil)

    def retranslateUi(self, Page_Acceuil):
        _translate = QtCore.QCoreApplication.translate
        Page_Acceuil.setWindowTitle(_translate("Page_Acceuil", "Page_Acceuil"))
        self.pushButton.setText(_translate("Page_Acceuil", "Recherche"))
        self.menuEtablissemnt.setTitle(_translate("Page_Acceuil", "Etablissement"))
        self.menuClasse.setTitle(_translate("Page_Acceuil", "Classe"))
        self.actionAjouter.setText(_translate("Page_Acceuil", "Ajouter"))
        self.actionVoir.setText(_translate("Page_Acceuil", "Voir"))
        self.actionAjouter_2.setText(_translate("Page_Acceuil", "Ajouter"))
        self.actionVoir_une_classe.setText(_translate("Page_Acceuil", "Voir une classe"))
        self.actionVoir_l_ensemble_des_classes.setText(_translate("Page_Acceuil", "Voir l\'ensemble des classes"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Page_Acceuil = QtWidgets.QMainWindow()
    ui = Ui_Page_Acceuil()
    ui.setupUi(Page_Acceuil)
    Page_Acceuil.show()
    sys.exit(app.exec_())

