# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableau_voir_ensemble_classe.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import first
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 598)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget()
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 621, 571))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(102, 255, 185);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 23))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuClasse = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menuClasse.setFont(font)
        self.menuClasse.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuClasse.setObjectName("menuClasse")
        self.menuNavigation = QtWidgets.QMenu(self.menubar)
        self.menuNavigation.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuNavigation.setObjectName("menuNavigation")
        MainWindow.setMenuBar(self.menubar)
        self.actionAjouter = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjouter.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter.setFont(font)
        self.actionAjouter.setObjectName("actionAjouter")
        self.actionVoir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoir.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionVoir.setFont(font)
        self.actionVoir.setObjectName("actionVoir")
        self.actionSupprimer = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSupprimer.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionSupprimer.setFont(font)
        self.actionSupprimer.setObjectName("actionSupprimer")
        if self.sender != None:
            self.actionRetour_L_acceuil = QtWidgets.QAction(MainWindow)
            icon4 = QtGui.QIcon()
            icon4.addPixmap(QtGui.QPixmap(":/newPrefix/2.08.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.actionRetour_L_acceuil.setIcon(icon4)
            self.actionRetour_L_acceuil.setObjectName("actionRetour_L_acceuil")
            self.menuNavigation.addAction(self.actionRetour_L_acceuil)
            self.actionRetour_L_acceuil.triggered.connect(self.retour_acceuil)
        self.actionRetour = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/2.08.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRetour.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionRetour.setFont(font)
        self.actionRetour.setObjectName("actionRetour")
        self.menuClasse.addAction(self.actionAjouter)
        self.menuClasse.addAction(self.actionVoir)
        self.menuClasse.addAction(self.actionSupprimer)
        self.menuNavigation.addAction(self.actionRetour)
        self.menubar.addAction(self.menuClasse.menuAction())
        self.menubar.addAction(self.menuNavigation.menuAction())

        self.actionAjouter.triggered.connect(self.ajouter)
        self.actionVoir.triggered.connect(self.voir_classe)
        self.actionSupprimer.triggered.connect(self.delet)
        self.actionRetour.triggered.connect(self.retour)

        self.v = QtWidgets.QVBoxLayout()
        self.v.addWidget(self.tableWidget)
        self.centralwidget.setLayout(self.v)

        self.retranslateUi(MainWindow, self.sender)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, sender):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Liste des classes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom établissement"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Année"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Niveau"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Série"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Numéro"))
        self.menuClasse.setTitle(_translate("MainWindow", "Classe"))
        self.menuNavigation.setTitle(_translate("MainWindow", "Navigation"))
        self.actionAjouter.setText(_translate("MainWindow", "Ajouter"))
        self.actionVoir.setText(_translate("MainWindow", "Voir"))
        self.actionSupprimer.setText(_translate("MainWindow", "Supprimer"))
        self.actionRetour.setText(_translate("MainWindow", "Retour"))
        if sender != None:
            self.actionRetour_L_acceuil.setText(_translate("MainWindow", "Retour à L\'acceuil"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

