# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableau_affichage.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import first
class Ui_MainWindow(object):
    def setupUi(self, V_CLASSE):
        V_CLASSE.setObjectName("V_CLASSE")
        V_CLASSE.resize(800, 600)
        V_CLASSE.setStyleSheet("background-color: rgb(11, 170, 75);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        V_CLASSE.setWindowIcon(icon)
        V_CLASSE.setStyleSheet("background-color: rgb(75, 170, 75);")
        self.centralwidget = QtWidgets.QWidget(V_CLASSE)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget()
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 751, 561))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget()
        self.v1 = QtWidgets.QVBoxLayout()
        self.v1.addWidget(self.tableWidget)
        self.tab.setLayout(self.v1)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 751, 531))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget()
        self.v2 = QtWidgets.QVBoxLayout()
        self.v2.addWidget(self.tableWidget_2)
        self.tab_2.setLayout(self.v2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 531))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget()
        self.v3 = QtWidgets.QVBoxLayout()
        self.v3.addWidget(self.tableWidget_3)
        self.tab_3.setLayout(self.v3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 751, 531))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.menubar = QtWidgets.QMenuBar(V_CLASSE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuEl_ve = QtWidgets.QMenu(self.menubar)
        self.menuEl_ve.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuEl_ve.setObjectName("menuEl_ve")
        self.menuNote = QtWidgets.QMenu(self.menubar)
        self.menuNote.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuNote.setObjectName("menuNote")
        self.menuExcel = QtWidgets.QMenu(self.menubar)
        self.menuExcel.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuExcel.setObjectName("menuExcel")
        self.menuAutre = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.menuAutre.setFont(font)
        self.menuAutre.setStyleSheet("background-color: rgb(11, 170, 75);")
        self.menuAutre.setObjectName("menuAutre")
        V_CLASSE.setMenuBar(self.menubar)
        self.actionAjouter = QtWidgets.QAction(V_CLASSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAjouter.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter.setFont(font)
        self.actionAjouter.setObjectName("actionAjouter")
        self.actionAjouter_plusieurs_l_ves = QtWidgets.QAction(V_CLASSE)
        self.actionAjouter_plusieurs_l_ves.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter_plusieurs_l_ves.setFont(font)
        self.actionAjouter_plusieurs_l_ves.setObjectName("actionAjouter_plusieurs_l_ves")
        self.actionModifier_un_l_ve = QtWidgets.QAction(V_CLASSE)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModifier_un_l_ve.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionModifier_un_l_ve.setFont(font)
        self.actionModifier_un_l_ve.setObjectName("actionModifier_un_l_ve")
        self.actionSupprimer_un_l_ve = QtWidgets.QAction(V_CLASSE)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/2.0.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSupprimer_un_l_ve.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionSupprimer_un_l_ve.setFont(font)
        self.actionSupprimer_un_l_ve.setObjectName("actionSupprimer_un_l_ve")
        self.actionAjouter_note = QtWidgets.QAction(V_CLASSE)
        self.actionAjouter_note.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionAjouter_note.setFont(font)
        self.actionAjouter_note.setObjectName("actionAjouter_note")
        self.actionModifier_note = QtWidgets.QAction(V_CLASSE)
        self.actionModifier_note.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionModifier_note.setFont(font)
        self.actionModifier_note.setObjectName("actionModifier_note")
        self.actionSupprimer = QtWidgets.QAction(V_CLASSE)
        self.actionSupprimer.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionSupprimer.setFont(font)
        self.actionSupprimer.setObjectName("actionSupprimer")
        self.actionImportation_de_la_liste_de_classe = QtWidgets.QAction(V_CLASSE)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportation_de_la_liste_de_classe.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionImportation_de_la_liste_de_classe.setFont(font)
        self.actionImportation_de_la_liste_de_classe.setObjectName("actionImportation_de_la_liste_de_classe")
        self.actionExportation_d_excel = QtWidgets.QAction(V_CLASSE)
        self.actionExportation_d_excel.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Walkway UltraBold")
        font.setPointSize(12)
        self.actionExportation_d_excel.setFont(font)
        self.actionExportation_d_excel.setObjectName("actionExportation_d_excel")
        self.actionRetour = QtWidgets.QAction(V_CLASSE)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/2.08.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRetour.setFont(font)
        self.actionRetour.setIcon(icon4)
        self.actionRetour.setObjectName("actionRetour")
        if self.sender != None:
            self.actionRetourAcceuil = QtWidgets.QAction(V_CLASSE)
            self.actionRetourAcceuil.setIcon(icon4)
            self.actionRetourAcceuil.setFont(font)
            self.actionRetourAcceuil.setObjectName("actionRetourAcceuil")
        self.menuEl_ve.addAction(self.actionAjouter)
        self.menuEl_ve.addAction(self.actionAjouter_plusieurs_l_ves)
        self.menuEl_ve.addAction(self.actionModifier_un_l_ve)
        self.menuEl_ve.addAction(self.actionSupprimer_un_l_ve)
        self.menuNote.addAction(self.actionAjouter_note)
        self.menuNote.addAction(self.actionModifier_note)
        self.menuNote.addAction(self.actionSupprimer)
        self.menuExcel.addAction(self.actionImportation_de_la_liste_de_classe)
        self.menuExcel.addAction(self.actionExportation_d_excel)
        self.menuAutre.addAction(self.actionRetour)
        self.menubar.addAction(self.menuEl_ve.menuAction())
        self.menubar.addAction(self.menuNote.menuAction())
        self.menubar.addAction(self.menuExcel.menuAction())
        self.menubar.addAction(self.menuAutre.menuAction())

        self.actionImportation_de_la_liste_de_classe.triggered.connect(self.importation)
        self.actionExportation_d_excel.triggered.connect(self.exportation)
        self.actionAjouter.triggered.connect(self.ajouter_eleve)

        self.actionAjouter_plusieurs_l_ves.triggered.connect(self.ajouter_many)

        self.actionModifier_un_l_ve.triggered.connect(self.modifier)
        self.actionSupprimer_un_l_ve.triggered.connect(self.delet)
        self.actionAjouter_note.triggered.connect(self.add_note)
        self.actionModifier_note.triggered.connect(self.modif)
        self.actionSupprimer.triggered.connect(self.verife_tab)
        self.actionRetour.triggered.connect(self.retour)
        if self.sender != None:
            self.actionRetourAcceuil.triggered.connect(self.retouracceuil)


        self.v = QtWidgets.QVBoxLayout()
        self.v.addWidget(self.tabWidget)
        self.centralwidget.setLayout(self.v)
        V_CLASSE.setCentralWidget(self.centralwidget)
        self.tabWidget.setCurrentIndex(0)

        self.retranslateUi(V_CLASSE, self.sender)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(V_CLASSE)

    def retranslateUi(self, V_CLASSE, sender):
        _translate = QtCore.QCoreApplication.translate
        V_CLASSE.setWindowTitle(_translate("V_CLASSE", "EDU-CLASSEUR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("V_CLASSE", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("V_CLASSE", "Prenoms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("V_CLASSE", " Trim/Sem 1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("V_CLASSE", "Nom"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("V_CLASSE", "Prenoms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("V_CLASSE", "Trim/Sem 2"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("V_CLASSE", "Nom"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("V_CLASSE", "Prenoms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("V_CLASSE", "Trimestre 3"))
        self.menuEl_ve.setTitle(_translate("V_CLASSE", "Elève"))
        self.menuNote.setTitle(_translate("V_CLASSE", "Note"))
        self.menuExcel.setTitle(_translate("V_CLASSE", "Excel"))
        self.menuAutre.setTitle(_translate("V_CLASSE", "Autre"))
        self.actionAjouter.setText(_translate("V_CLASSE", "Ajouter un élève"))
        self.actionAjouter_plusieurs_l_ves.setText(_translate("V_CLASSE", "Ajouter plusieurs élèves"))
        self.actionModifier_un_l_ve.setText(_translate("V_CLASSE", "Modifier un élève"))
        self.actionSupprimer_un_l_ve.setText(_translate("V_CLASSE", "Supprimer un élève"))
        self.actionAjouter_note.setText(_translate("V_CLASSE", "Ajouter note"))
        self.actionModifier_note.setText(_translate("V_CLASSE", "Modifier note"))
        self.actionSupprimer.setText(_translate("V_CLASSE", "Supprimer"))
        self.actionImportation_de_la_liste_de_classe.setText(_translate("V_CLASSE", "Importation de la liste de classe"))
        self.actionExportation_d_excel.setText(_translate("V_CLASSE", "Exportation vers excel"))
        self.actionRetour.setText(_translate("V_CLASSE", "Retour"))
        if sender != None:
            self.actionRetourAcceuil.setText(_translate("V_CLASSE", "Retour à l'acceuil"))
            self.actionRetourAcceuil.setToolTip(_translate("V_CLASSE", "Retour"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

